use_frameworks!

platform :ios, '10.0'

target 'LottieAnimationKit_Example' do
  pod 'LottieAnimationKit', :path => '../'

  target 'LottieAnimationKit_Tests' do
    inherit! :search_paths

    
  end
end
