use_frameworks!

platform :ios, '10.0'

target 'LottieAnimationKit_Example' do
  pod 'LottieAnimationKit', :path => '../'
  pod 'lottie-ios','2.5.3'
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
          
          # xcode15 环境问题
          xcconfig_path = config.base_configuration_reference.real_path
          xcconfig = File.read(xcconfig_path)
          xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
          File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
          
        end
      end
    end
end
